# zizmor configuration
# https://docs.zizmor.sh/configuration/

rules:
  # cargo-dist requires workflow-level write permissions for GitHub Releases
  excessive-permissions:
    ignore:
      - release.yml

  # cargo-dist uses matrix expansion for cross-platform builds
  # These are safe because the values come from dist's own plan output
  template-injection:
    ignore:
      - release.yml
